# Generated by Django 4.1 on 2022-10-25 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='vvod', max_length=50, verbose_name='название')),
                ('anons', models.CharField(default='vvod', max_length=250, verbose_name='АНОНС')),
                ('full_text', models.TextField(verbose_name='статья')),
                ('date', models.DateTimeField(verbose_name='ВРЕМЯ АНОНСА')),
            ],
        ),
    ]
